import { ComponentFormat, ExportOptions, ExportResult } from './types/export'

export class ExportService {
  private supportedFormats: ComponentFormat[] = ['tsx', 'jsx', 'vue', 'svelte']

  async exportComponent(
    componentCode: string,
    options: ExportOptions
  ): Promise<ExportResult> {
    if (!componentCode || componentCode.trim().length === 0) {
      throw new Error('Component code cannot be empty')
    }

    if (!this.supportedFormats.includes(options.format)) {
      throw new Error(`Unsupported format: ${options.format}. Supported: ${this.supportedFormats.join(', ')}`)
    }

    const transformed = await this.transform(componentCode, options)
    const filename = this.buildFilename(options)

    return {
      filename,
      content: transformed,
      format: options.format,
      sizeBytes: Buffer.byteLength(transformed, 'utf8'),
    }
  }

  private async transform(code: string, options: ExportOptions): Promise<string> {
    let result = code

    if (options.format === 'jsx') {
      result = result.replace(/: React\.FC/g, '').replace(/: FC/g, '')
    }

    if (options.addHeader) {
      result = `// Generated by uigen — ${new Date().toISOString()}\n${result}`
    }

    return result
  }

  private buildFilename(options: ExportOptions): string {
    const ext = options.format === 'vue' ? 'vue' : options.format === 'svelte' ? 'svelte' : options.format
    return `${options.componentName ?? 'Component'}.${ext}`
  }

  getSupportedFormats(): ComponentFormat[] {
    return [...this.supportedFormats]
  }
}
